# Generated by Django 6.0.4 on 2026-05-14 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excavations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_excavations', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='participating_excavations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'excavations',
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('excavation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='excavations.excavations')),
            ],
            options={
                'db_table': 'sectors',
            },
        ),
    ]
